default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username:
  password:

development:
  <<: *default
  database: github_api_app_development

test:
  <<: *default
  database: github_api_app_test

production:
  <<: *default
  database: github_api_app_production
  username: github_api_app
  password: <%= ENV['GITHUB_API_APP_DATABASE_PASSWORD'] %>
